package kissalaMain.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kissalaMain.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.08.10 14:02:41 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class KissalaTest {



  // Generated by ComTest BEGIN
  /** testToString189 */
  @Test
  public void testToString189() {    // Kissala: 189
    Kissala kissala = new Kissala(); 
    kissala.taytaKissalaTiedoilla(); 
    kissala.toString().equals(
    "{\n" +
    "\"id\": \"1\",\n" +
    "\"Kissalan nimi\": \"Testikissala\",\n" +
    "\"Kasvattajan etunimi\": \"Testietunimi\",\n" +
    "\"Kasvattajan sukunimi\": \"Testisukunimi\",\n" +
    "\"Katuosoite\": \"Testikatu\",\n" +
    "\"Postinumero\": \"12345\",\n" +
    "\"Paikkakunta\": \"Testipaikkakunta\"\n" +
    "}"
    ); 
  } // Generated by ComTest END
}