package kissalaMain.test;
// Generated by ComTest BEGIN

import kissalaMain.Kissa;
import org.junit.Test;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.08.10 14:00:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class KissaTest {



  // Generated by ComTest BEGIN
  /** testToString298 */
  @Test
  public void testToString298() {    // Kissa: 298
    Kissa kissa = new Kissa(); 
    kissa.taytaKissaTiedoilla(); 
    kissa.toString().equals(
    "{\n" +
    "  \"id\": \"1\",\n" +
    "  \"Kissalan ID\": \"1\",\n" +
    "  \"Rekisterinumero\": \"123456789\",\n" +
    "  \"Nimi\": \"Kissa\",\n" +
    "  \"Kutsumanimi\": \"Helmi\",\n" +
    "  \"Rotu\": \"Brittiläinen lyhytkarva\",\n" +
    "  \"Veriryhmä\": \"A\",\n" +
    "  \"Kotiosoite\": \"Kissakuja 7\",\n" +
    "  \"Postinumero\": \"90100\",\n" +
    "  \"Syntymäaika\": \"01.01.2020\",\n" +
    "  \"Isä\": \"Mese\",\n" +
    "  \"Äiti\": \"Siru\",\n" +
    "  \"Sijoitettu\": \"kyllä\",\n" +
    "  \"Pennut\": \"Ei\",\n" +
    "  \"FIV\": \"neg\",\n" +
    "  \"FeLV\": \"neg\",\n" +
    "}"
    ); 
  } // Generated by ComTest END
}